#
# ReArch Repository Configuration
#

[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
ILoveCandy

[rearch]
SigLevel = Optional TrustAll
Server = file:///home/revy/Downloads/Kimi_Agent_ReArch OS Custom Repo Tools/rearch-os-dev/rearch-repo/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
